# windows环境下的配置

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///fantasy-blog
    username: root
    password: 1234

# 静态文件上传访问路径 Linux环境如 :/home/My Blog/upload
upload:
  path: D:/tempImages/upload
  access:
    path: /images/**
  resources:
    locations: file:${upload.path}

