server:
  port: 8090

spring:
  main:
    allow-circular-references: true
  mvc: # 解决引入knife4j产生的问题
    pathmatch:
      matching-strategy: ant_path_matcher
      
  profiles: # 设置环境配置文件
    active: windows # 启用application-linux或windows


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



